### ISSUE TITLE
Find A position error of mesh vertices in GrassPointCloudRenderer.cs

### ISSUE THREAD

**Issue by zobuzz** [WorldOfZero/UnityVisualizations#8]
WorldOfZero,  I watched your tutorial video a lot . That is amazing !!
And I found a transform position of mesh vertices in  GrassPointCloudRenderer.cs .

                positions.Add(origin);
this is not correct , because we add world position of points into mesh , and unity Transform will do that transform again, so you may see the transform of points is calculated twice . 
that line should be :

                positions.Add(origin - transform.position);
And finally , bro, your work helped so many developers ,keep doing it !! Love u a lot , and thanks !!

**Comment by runewake2** [comment]
Hey, thanks so much for point this out! I'll push out a fix later this week. There are a few other PR's that I need to clean up as well.
